# Generated by Django 5.1 on 2024-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='mobile_no',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
