# Generated by Django 5.1 on 2024-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_user_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhaar_image',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_files/'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='aadhaar_num',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='collage_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
