# Generated by Django 5.1 on 2024-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_user_details_aadhaar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
