# Generated by Django 5.1 on 2024-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_user_details_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='user_details',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user_details',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=6000.0, max_digits=10),
        ),
    ]
