# Generated by Django 5.1 on 2024-10-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_user_details_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='management.user_details')),
            ],
        ),
    ]
