# Generated by Django 5.1 on 2024-10-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_paymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
