# Generated by Django 5.1 on 2024-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='service_type',
            field=models.CharField(choices=[('AF', 'Accommodation & Food'), ('FO', 'Food Only')], default='AF', max_length=2),
        ),
    ]
