# Generated by Django 5.1 on 2024-10-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_user_details_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
