# Generated by Django 5.1 on 2024-09-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_details',
            options={'ordering': ['-payment_date']},
        ),
    ]
