# Generated by Django 5.1 on 2024-10-13 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_payment_details_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_details',
            new_name='PaymentDetails',
        ),
    ]
