# Generated by Django 5.1 on 2024-10-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_payment_details_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
