# Generated by Django 5.1 on 2024-10-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_paymentdetails_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
